export const mockedCompanies = [
  {
    "question": "Чому ми з МІСТОХАБ?",
    "answer": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "_id": "2c305bd9-9f4f-49e8-aa83-23f9c10d4d9b",
    "id": 2,
    "name": "Simply because it is pain...",
    "logoURL": "/src/assets/JoinUs/images/webp/cafe-oval@2x.webp",
    "link": " http://ugtc.com.ua"
  },
  {
    "question": "Чому ми з МІСТОХАБ?",
    "answer": "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",
    "_id": "2c305bd9-9f4f-49e8-aa83-23f9c10d4d9b",
    "id": 2,
    "name": "Where can I get some?",
    "logoURL": "/src/assets/JoinUs/images/jpg/cafe.jpg",
    "link": " http://ugtc.com.ua"
  },
  {
    "question": "Чому ми з МІСТОХАБ?",
    "answer": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "_id": "2c305bd9-9f4f-49e8-aa83-23f9c10d4d9b",
    "id": 2,
    "name": "Simply because it is pain...",
    "logoURL": "/src/assets/JoinUs/images/webp/cafe-oval@2x.webp",
    "link": " http://ugtc.com.ua"
  },
  {
    "question": "Чому ми з МІСТОХАБ?",
    "answer": "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",
    "_id": "2c305bd9-9f4f-49e8-aa83-23f9c10d4d9b",
    "id": 2,
    "name": "Where can I get some?",
    "logoURL": "/src/assets/JoinUs/images/jpg/cafe.jpg",
    "link": " http://ugtc.com.ua"
  },
  {
    "question": "Чому ми з МІСТОХАБ?",
    "answer": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "_id": "2c305bd9-9f4f-49e8-aa83-23f9c10d4d9b",
    "id": 2,
    "name": "Simply because it is pain...",
    "logoURL": "/src/assets/JoinUs/images/webp/cafe-oval@2x.webp",
    "link": " http://ugtc.com.ua"
  },
  {
    "question": "Чому ми з МІСТОХАБ?",
    "answer": "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",
    "_id": "2c305bd9-9f4f-49e8-aa83-23f9c10d4d9b",
    "id": 2,
    "name": "Where can I get some?",
    "logoURL": "/src/assets/JoinUs/images/jpg/cafe.jpg",
    "link": " http://ugtc.com.ua"
  },
  {
    "question": "Чому ми з МІСТОХАБ?",
    "answer": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "_id": "2c305bd9-9f4f-49e8-aa83-23f9c10d4d9b",
    "id": 2,
    "name": "Simply because it is pain...",
    "logoURL": "/src/assets/JoinUs/images/webp/cafe-oval@2x.webp",
    "link": " http://ugtc.com.ua"
  },
  {
    "question": "Чому ми з МІСТОХАБ?",
    "answer": "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",
    "_id": "2c305bd9-9f4f-49e8-aa83-23f9c10d4d9b",
    "id": 2,
    "name": "Where can I get some?",
    "logoURL": "/src/assets/JoinUs/images/jpg/cafe.jpg",
    "link": " http://ugtc.com.ua"
  },
  {
    "question": "Чому ми з МІСТОХАБ?",
    "answer": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "_id": "2c305bd9-9f4f-49e8-aa83-23f9c10d4d9b",
    "id": 2,
    "name": "Simply because it is pain...",
    "logoURL": "/src/assets/JoinUs/images/webp/cafe-oval@2x.webp",
    "link": " http://ugtc.com.ua"
  },
  {
    "question": "Чому ми з МІСТОХАБ?",
    "answer": "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",
    "_id": "2c305bd9-9f4f-49e8-aa83-23f9c10d4d9b",
    "id": 2,
    "name": "Where can I get some?",
    "logoURL": "/src/assets/JoinUs/images/jpg/cafe.jpg",
    "link": " http://ugtc.com.ua"
  },
  {
    "question": "Чому ми з МІСТОХАБ?",
    "answer": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "_id": "2c305bd9-9f4f-49e8-aa83-23f9c10d4d9b",
    "id": 2,
    "name": "Simply because it is pain...",
    "logoURL": "/src/assets/JoinUs/images/webp/cafe-oval@2x.webp",
    "link": " http://ugtc.com.ua"
  },
  {
    "question": "Чому ми з МІСТОХАБ?",
    "answer": "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",
    "_id": "2c305bd9-9f4f-49e8-aa83-23f9c10d4d9b",
    "id": 2,
    "name": "Where can I get some?",
    "logoURL": "/src/assets/JoinUs/images/jpg/cafe.jpg",
    "link": " http://ugtc.com.ua"
  },
  {
    "question": "Чому ми з МІСТОХАБ?",
    "answer": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "_id": "2c305bd9-9f4f-49e8-aa83-23f9c10d4d9b",
    "id": 2,
    "name": "Simply because it is pain...",
    "logoURL": "/src/assets/JoinUs/images/webp/cafe-oval@2x.webp",
    "link": " http://ugtc.com.ua"
  },
  {
    "question": "Чому ми з МІСТОХАБ?",
    "answer": "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",
    "_id": "2c305bd9-9f4f-49e8-aa83-23f9c10d4d9b",
    "id": 2,
    "name": "Where can I get some?",
    "logoURL": "/src/assets/JoinUs/images/jpg/cafe.jpg",
    "link": " http://ugtc.com.ua"
  },
  {
    "question": "Чому ми з МІСТОХАБ?",
    "answer": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "_id": "2c305bd9-9f4f-49e8-aa83-23f9c10d4d9b",
    "id": 2,
    "name": "Simply because it is pain...",
    "logoURL": "/src/assets/JoinUs/images/webp/cafe-oval@2x.webp",
    "link": " http://ugtc.com.ua"
  },
  {
    "question": "Чому ми з МІСТОХАБ?",
    "answer": "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",
    "_id": "2c305bd9-9f4f-49e8-aa83-23f9c10d4d9b",
    "id": 2,
    "name": "Where can I get some?",
    "logoURL": "/src/assets/JoinUs/images/jpg/cafe.jpg",
    "link": " http://ugtc.com.ua"
  },
  {
    "question": "Чому ми з МІСТОХАБ?",
    "answer": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "_id": "2c305bd9-9f4f-49e8-aa83-23f9c10d4d9b",
    "id": 2,
    "name": "Simply because it is pain...",
    "logoURL": "/src/assets/JoinUs/images/webp/cafe-oval@2x.webp",
    "link": " http://ugtc.com.ua"
  },
  {
    "question": "Чому ми з МІСТОХАБ?",
    "answer": "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",
    "_id": "2c305bd9-9f4f-49e8-aa83-23f9c10d4d9b",
    "id": 2,
    "name": "Where can I get some?",
    "logoURL": "/src/assets/JoinUs/images/jpg/cafe.jpg",
    "link": " http://ugtc.com.ua"
  },
  {
    "question": "Чому ми з МІСТОХАБ?",
    "answer": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "_id": "2c305bd9-9f4f-49e8-aa83-23f9c10d4d9b",
    "id": 2,
    "name": "Simply because it is pain...",
    "logoURL": "/src/assets/JoinUs/images/webp/cafe-oval@2x.webp",
    "link": " http://ugtc.com.ua"
  },
  {
    "question": "Чому ми з МІСТОХАБ?",
    "answer": "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",
    "_id": "2c305bd9-9f4f-49e8-aa83-23f9c10d4d9b",
    "id": 2,
    "name": "Where can I get some?",
    "logoURL": "/src/assets/JoinUs/images/jpg/cafe.jpg",
    "link": " http://ugtc.com.ua"
  },
  {
    "question": "Чому ми з МІСТОХАБ?",
    "answer": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "_id": "2c305bd9-9f4f-49e8-aa83-23f9c10d4d9b",
    "id": 2,
    "name": "Simply because it is pain...",
    "logoURL": "/src/assets/JoinUs/images/webp/cafe-oval@2x.webp",
    "link": " http://ugtc.com.ua"
  },
  {
    "question": "Чому ми з МІСТОХАБ?",
    "answer": "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",
    "_id": "2c305bd9-9f4f-49e8-aa83-23f9c10d4d9b",
    "id": 2,
    "name": "Where can I get some?",
    "logoURL": "/src/assets/JoinUs/images/jpg/cafe.jpg",
    "link": " http://ugtc.com.ua"
  },
];

export const mockedPersons = [
  {
    "_id": "f46c5966-379a-49c8-9c2d-c3ee9aee23fe",
    "id": 37,
    "otherLink": null,
    "answer": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "firstName": "Lorem",
    "secondName": "Ipsum ",
    "type": "ІТ-підприємець",
    "imageURL": "/src/assets/JoinUs/images//webp/person-circle@2x.webp",
    "facebook": null,
    "instagram": "https://www.instagram.com/",
    "question": "Чому я з МІСТОХАБ? "
  },
  {
    "_id": "f46c5966-379a-49c8-9c2d-c3ee9aee23fe",
    "id": 37,
    "otherLink": null,
    "answer": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
    "firstName": "Neque porro quisquam",
    "secondName": "est qui dolorem ipsum",
    "type": `It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
    "imageURL": "/src/assets/AccumulatedMoney/back-for-mobile.png",
    "facebook": "https://www.facebook.com/",
    "instagram": "",
    "question": "Чому я з МІСТОХАБ? "
  },
  {
    "_id": "f46c5966-379a-49c8-9c2d-c3ee9aee23fe",
    "id": 37,
    "otherLink": null,
    "answer": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "firstName": "Lorem",
    "secondName": "Ipsum ",
    "type": "ІТ-підприємець",
    "imageURL": "/src/assets/JoinUs/images//webp/person-circle@2x.webp",
    "facebook": null,
    "instagram": "https://www.instagram.com/",
    "question": "Чому я з МІСТОХАБ? "
  },
  {
    "_id": "f46c5966-379a-49c8-9c2d-c3ee9aee23fe",
    "id": 37,
    "otherLink": null,
    "answer": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
    "firstName": "Neque porro quisquam",
    "secondName": "est qui dolorem ipsum",
    "type": `It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
    "imageURL": "/src/assets/AccumulatedMoney/back-for-mobile.png",
    "facebook": "https://www.facebook.com/",
    "instagram": "",
    "question": "Чому я з МІСТОХАБ? "
  },
  {
    "_id": "f46c5966-379a-49c8-9c2d-c3ee9aee23fe",
    "id": 37,
    "otherLink": null,
    "answer": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "firstName": "Lorem",
    "secondName": "Ipsum ",
    "type": "ІТ-підприємець",
    "imageURL": "/src/assets/JoinUs/images//webp/person-circle@2x.webp",
    "facebook": null,
    "instagram": "https://www.instagram.com/",
    "question": "Чому я з МІСТОХАБ? "
  },
  {
    "_id": "f46c5966-379a-49c8-9c2d-c3ee9aee23fe",
    "id": 37,
    "otherLink": null,
    "answer": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
    "firstName": "Neque porro quisquam",
    "secondName": "est qui dolorem ipsum",
    "type": `It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
    "imageURL": "/src/assets/AccumulatedMoney/back-for-mobile.png",
    "facebook": "https://www.facebook.com/",
    "instagram": "",
    "question": "Чому я з МІСТОХАБ? "
  },
  {
    "_id": "f46c5966-379a-49c8-9c2d-c3ee9aee23fe",
    "id": 37,
    "otherLink": null,
    "answer": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "firstName": "Lorem",
    "secondName": "Ipsum ",
    "type": "ІТ-підприємець",
    "imageURL": "/src/assets/JoinUs/images//webp/person-circle@2x.webp",
    "facebook": null,
    "instagram": "https://www.instagram.com/",
    "question": "Чому я з МІСТОХАБ? "
  },
  {
    "_id": "f46c5966-379a-49c8-9c2d-c3ee9aee23fe",
    "id": 37,
    "otherLink": null,
    "answer": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
    "firstName": "Neque porro quisquam",
    "secondName": "est qui dolorem ipsum",
    "type": `It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
    "imageURL": "/src/assets/AccumulatedMoney/back-for-mobile.png",
    "facebook": "https://www.facebook.com/",
    "instagram": "",
    "question": "Чому я з МІСТОХАБ? "
  },
  {
    "_id": "f46c5966-379a-49c8-9c2d-c3ee9aee23fe",
    "id": 37,
    "otherLink": null,
    "answer": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "firstName": "Lorem",
    "secondName": "Ipsum ",
    "type": "ІТ-підприємець",
    "imageURL": "/src/assets/JoinUs/images//webp/person-circle@2x.webp",
    "facebook": null,
    "instagram": "https://www.instagram.com/",
    "question": "Чому я з МІСТОХАБ? "
  },
  {
    "_id": "f46c5966-379a-49c8-9c2d-c3ee9aee23fe",
    "id": 37,
    "otherLink": null,
    "answer": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
    "firstName": "Neque porro quisquam",
    "secondName": "est qui dolorem ipsum",
    "type": `It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
    "imageURL": "/src/assets/AccumulatedMoney/back-for-mobile.png",
    "facebook": "https://www.facebook.com/",
    "instagram": "",
    "question": "Чому я з МІСТОХАБ? "
  },
  {
    "_id": "f46c5966-379a-49c8-9c2d-c3ee9aee23fe",
    "id": 37,
    "otherLink": null,
    "answer": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "firstName": "Lorem",
    "secondName": "Ipsum ",
    "type": "ІТ-підприємець",
    "imageURL": "/src/assets/JoinUs/images//webp/person-circle@2x.webp",
    "facebook": null,
    "instagram": "https://www.instagram.com/",
    "question": "Чому я з МІСТОХАБ? "
  },
  {
    "_id": "f46c5966-379a-49c8-9c2d-c3ee9aee23fe",
    "id": 37,
    "otherLink": null,
    "answer": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
    "firstName": "Neque porro quisquam",
    "secondName": "est qui dolorem ipsum",
    "type": `It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
    "imageURL": "/src/assets/AccumulatedMoney/back-for-mobile.png",
    "facebook": "https://www.facebook.com/",
    "instagram": "",
    "question": "Чому я з МІСТОХАБ? "
  },
  {
    "_id": "f46c5966-379a-49c8-9c2d-c3ee9aee23fe",
    "id": 37,
    "otherLink": null,
    "answer": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "firstName": "Lorem",
    "secondName": "Ipsum ",
    "type": "ІТ-підприємець",
    "imageURL": "/src/assets/JoinUs/images//webp/person-circle@2x.webp",
    "facebook": null,
    "instagram": "https://www.instagram.com/",
    "question": "Чому я з МІСТОХАБ? "
  },
  {
    "_id": "f46c5966-379a-49c8-9c2d-c3ee9aee23fe",
    "id": 37,
    "otherLink": null,
    "answer": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
    "firstName": "Neque porro quisquam",
    "secondName": "est qui dolorem ipsum",
    "type": `It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
    "imageURL": "/src/assets/AccumulatedMoney/back-for-mobile.png",
    "facebook": "https://www.facebook.com/",
    "instagram": "",
    "question": "Чому я з МІСТОХАБ? "
  },
  {
    "_id": "f46c5966-379a-49c8-9c2d-c3ee9aee23fe",
    "id": 37,
    "otherLink": null,
    "answer": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "firstName": "Lorem",
    "secondName": "Ipsum ",
    "type": "ІТ-підприємець",
    "imageURL": "/src/assets/JoinUs/images//webp/person-circle@2x.webp",
    "facebook": null,
    "instagram": "https://www.instagram.com/",
    "question": "Чому я з МІСТОХАБ? "
  },
  {
    "_id": "f46c5966-379a-49c8-9c2d-c3ee9aee23fe",
    "id": 37,
    "otherLink": null,
    "answer": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
    "firstName": "Neque porro quisquam",
    "secondName": "est qui dolorem ipsum",
    "type": `It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
    "imageURL": "/src/assets/AccumulatedMoney/back-for-mobile.png",
    "facebook": "https://www.facebook.com/",
    "instagram": "",
    "question": "Чому я з МІСТОХАБ? "
  },
  {
    "_id": "f46c5966-379a-49c8-9c2d-c3ee9aee23fe",
    "id": 37,
    "otherLink": null,
    "answer": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "firstName": "Lorem",
    "secondName": "Ipsum ",
    "type": "ІТ-підприємець",
    "imageURL": "/src/assets/JoinUs/images//webp/person-circle@2x.webp",
    "facebook": null,
    "instagram": "https://www.instagram.com/",
    "question": "Чому я з МІСТОХАБ? "
  },
  {
    "_id": "f46c5966-379a-49c8-9c2d-c3ee9aee23fe",
    "id": 37,
    "otherLink": null,
    "answer": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
    "firstName": "Neque porro quisquam",
    "secondName": "est qui dolorem ipsum",
    "type": `It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
    "imageURL": "/src/assets/AccumulatedMoney/back-for-mobile.png",
    "facebook": "https://www.facebook.com/",
    "instagram": "",
    "question": "Чому я з МІСТОХАБ? "
  },
]